#!/bin/sh
#
# Extract parst from reduplicated files, this is useful to build a
# 'part word' lexicon when the reduplicated lexical items are not
# tokenized togehter.
#
# FIXME: Currently we assume all parts of a reduplicated item can be
# inflected. These should be marked in the lexicon file and
# restricted.
#
# TODO: Make this part of the build system.
#

cat<<EOF
!
! DO NOT edit this file.
!
! This file is regnerated from the lexicon file reduplication
!
EOF
IFS='
'
for line in `grep '^[^!].*% ' reduplication`;do 
    p1=`echo $line|cut -d\% -f1` 
    p2=`echo $line|sed 's/.*% \([^ ]*\) .*/\1/'`
    pos=`echo $line|sed 's/.*\([A-Z][a-z]*\);.*/\1/'`
    echo "$p1 ${pos}PartLast;"
    echo "$p2 ${pos}PartLast;"
done | sort |uniq | column -t

